#!/usr/bin/env bash
# script that configures an Ubuntu server
# with the requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/new_hosts
sed -i s/127.0.0.1/127.0.0.2/ ~/new_hosts
echo "8.8.8.8 facebook.com" >> ~/new_hosts
cp -f ~/new_hosts/etc/hosts 
